#!/usr/bin/env bash
#display listening ports
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
ss -tunlp | awk '
/^udp|^tcp/ {
    pid_prog = ($6 ~ /users:/) ? gensub(/.*users:\(\("([^"]+)",pid=([0-9]+).*/, "\\2/\\1", 1) : ""
    printf "%-5s %-6s %-6s %-23s %-23s %-11s %s\n", $1, $2, $3, $4, $5, $6, pid_prog
}'

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
ss -xlnp | awk '
/^u/ {
    pid_prog = ($6 ~ /users:/) ? gensub(/.*users:\(\("([^"]+)",pid=([0-9]+).*/, "\\2/\\1", 1) : ""
    path = ($7 != "" ? $7 : "")
    printf "%-5s %-6s %-12s %-10s %-13s %-8s %-18s %s\n", $1, $2, $3, $4, $5, "", pid_prog, path
}'
