#!/usr/bin/env bash
#display listening ports
echo "Active Internet connections (only servers)"
netstat -tulnp | grep -E '^(tcp|udp)'

echo "Active UNIX domain sockets (only servers)"
netstat -lxnp | grep -E '^unix'
